# Generated by Django 4.2.6 on 2025-08-14 23:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('telefono', models.CharField(max_length=15, unique=True)),
                ('referencia_moto', models.CharField(blank=True, max_length=100, null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ClienteFrecuente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_cliente', models.CharField(max_length=50)),
                ('referencia_motocicleta', models.CharField(max_length=30)),
                ('motivo_reparacion', models.CharField(max_length=50)),
                ('numero_telefono', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Turno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_cliente', models.CharField(max_length=100)),
                ('referencia_motocicleta', models.CharField(blank=True, max_length=100, null=True)),
                ('numero_telefono', models.CharField(blank=True, max_length=15, null=True)),
                ('motivo_reparacion', models.TextField(blank=True, null=True)),
                ('numero_turno', models.IntegerField(blank=True, null=True, unique=True)),
                ('orden', models.IntegerField(blank=True, null=True)),
                ('cliente_frecuente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='turnos_app.clientefrecuente')),
            ],
            options={
                'ordering': ['orden'],
            },
        ),
    ]
