# Generated by Django 4.2.6 on 2025-08-21 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turnos_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='turno',
            name='en_reparacion',
            field=models.BooleanField(default=False),
        ),
    ]
