# Generated by Django 4.2.9 on 2026-03-09 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turnos_app', '0002_turno_en_reparacion'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cliente',
        ),
        migrations.AddField(
            model_name='clientefrecuente',
            name='actualizado_en',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='clientefrecuente',
            name='creado_en',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='clientefrecuente',
            name='placa',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='turno',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='turno',
            name='fecha_finalizacion',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='turno',
            name='finalizado',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='turno',
            name='numero_turno',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
